version: '3.9'
services:
  auth:
    environment:
      AUTH_CONFIG: config.DevelopmentConfig
    volumes:
      - ./authorization/src:/app
    command: flask --app main:app --debug run --host=0.0.0.0
