version: '3.9'
services:
  auth:
    build:
      context: ./authorization
    environment:
      - AUTH_CONFIG=config.ProductionConfig
      - GUNICORN_CMD_ARGS
      - POSTGRES_PASSWORD
      - POSTGRES_USER
      - POSTGRES_DB
      - POSTGRES_HOST
      - REDIS_HOST
      - SECRET_KEY
      - TOKEN_SECRET_KEY
    depends_on:
      - db
      - redis
    ports:
      - '5000:5000'
  redis:
    image: redis:6-alpine
  db:
    image: postgres:14-alpine
    environment:
      - POSTGRES_PASSWORD
      - POSTGRES_USER
      - POSTGRES_DB
      - PGDATA=/var/lib/postgresql/data
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
